project_name: network_exporter
dist: artifacts
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    main: .
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    binary: network_exporter
archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}-{{ .Version }}.{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
    wrap_in_directory: true
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
nfpms:
  - vendor: Sebastian YEPES
    homepage: "https://github.com/syepes/network_exporter"
    maintainer: Sebastian YEPES
    description: "Network Prometheus Exporter"
    license: Apache 2.0 License
    formats:
      - deb
      - rpm
    bindir: /usr/bin
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
