name: build

on:
  push:
    branches: master
    paths-ignore:
      - "dist/**"
      - "**.md"

jobs:
  build:
    name: build images and push
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: docker buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
          qemu-version: latest

      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Get tag version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})

      - name: build and push (tag)
        run: make build-push
        env:
          VERSION: ${{steps.vars.outputs.tag}}

      - name: build and push (master)
        run: make build-push
