name: build

on:
  push:
    branches: master
    tags:
      - "*"
    paths-ignore:
      - "dist/**"
      - "**.md"

jobs:
  build:
    name: build images and push
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: docker buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
          qemu-version: latest

      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: repo info
        id: vars
        run: |
          echo ::set-output name=repo_tag::${GITHUB_REF#refs/*/}

      - name: build and push (tag)
        if: startsWith( github.ref, 'refs/tags/')
        run: make build-push
        env:
          VERSION: ${{steps.vars.outputs.repo_tag}}

      - name: build and push (master)
        if: "github.ref == 'refs/heads/master'"
        run: make build-push

  releases-matrix:
    name: Binary Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.22
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "./network_exporter"
          binary_name: "network_exporter"
          ldflags: "-s -w"
          extra_files: README.md LICENSE.md
