name: build

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - "dist/**"
      - "**.md"

jobs:
  build:
    name: build images
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: docker buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
          qemu-version: latest

      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: repo info
        id: vars
        run: |
          echo ::set-output name=repo_tag::${GITHUB_REF#refs/*/}

      - name: build (master)
        if: "github.ref == 'refs/heads/master'"
        run: make build
