name: build

on:
  push:
    branches: master
    paths-ignore:
      - "dist/**"
      - "**.md"

jobs:
  build:
    name: build images and push
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: docker buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
          qemu-version: latest

      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: find repo names
        id: vars
        run: |
          echo ::set-output name=repo_name::${GITHUB_REF#refs/*/}
          echo ::set-output name=repo_branch::${GITHUB_REF#refs/heads/}
          echo ::set-output name=repo_tag::${GITHUB_REF#refs/tags/}

      - name: build and push (tag)
        run: make build-push
        env:
          VERSION: ${{steps.vars.outputs.repo_tag}}

      - name: build and push (master)
        run: make build-push
