name: build

on:
  push:
    tags:
      - "v*.*.*"
      - "*.*.*"
    paths-ignore:
      - "dist/**"
      - "**.md"

jobs:
  build:
    name: build images and push
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: repo info
        id: vars
        run: |
          echo ::set-output name=repo_tag::${GITHUB_REF#refs/*/}

      - name: build and push (tag)
        if: startsWith( github.ref, 'refs/tags/')
        run: make build-push
        env:
          VERSION: ${{steps.vars.outputs.repo_tag}}

      - name: build and push (latest)
        if: startsWith( github.ref, 'refs/tags/')
        run: make build-push
        env:
          VERSION: latest

  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          check-latest: true
          go-version-file: go.mod
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
